### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by SmallOyster** [zhangjingye03/zxcarddumpreader#1]
想问问几个使用上的问题(如果你做完了)

▲该咋用……要读卡器吗？

▲readme的“自行获取dump文件”咋搞？

▲能获取啥信息啊？

**Comment by zhangjingye03** [comment]
- 初期不考虑读卡器读取支持，后期考虑引用别人的开源库在linux上实现读取
- dump文件可以用相关读卡器软件获取
- 目前能获取到的信息：总消费次数，前两次消费的余额，消费机id，连续消费次数，饭卡UID，饭卡背面编号(要算)，饭卡是否损坏等，详见源码的`zxcard_sec1`结构体

**Comment by SmallOyster** [comment]
牛b，那能不能看到余额？

卡片损坏？

在linux读取？！

**Comment by ghost** [comment]
噫，同校的大神，学校的饭卡不是和数据库连的吗，所以做这个只是为了获取饭卡的记录？

**Comment by zhangjingye03** [comment]
理论上饭卡消费的POS机是和数据库连接的，不过饭卡上保留了一定的数据

**Comment by SmallOyster** [comment]
@zhangjingye03 数据库是本地的吧。做完了教教我们怎么刷呗
